### ISSUE TITLE
Test engine can't find Network's unit tests

### ISSUE THREAD

**Issue by Mirandatz** [CoreOpenMMO/CoreOpenMMO#34]
Investigate what's wrong with the unit tests engine. Since the 'clean up merge', the engine can't find COMMO.Network's tests.

**Comment by Marcelo-Petrucelli** [comment]
Seems to be solver by 458fbba237a76dd0d89150f0638572a55e83a814, with other fixes.

**Comment by Marcelo-Petrucelli** [comment]
[3/6/2018 4:54:11 PM Warning] Test run will use DLL(s) built for framework Framework45 and platform X86. Following DLL(s) will not be part of run: 
COMMO.Network.Tests.dll is built for Framework FrameworkCore10 and Platform X64.

**Comment by Marcelo-Petrucelli** [comment]
Well, that problem was fixed. But now we're facing:

> [3/6/2018 8:23:43 PM Warning] [MSTest][Discovery][\bin\x64\Release\netcoreapp2.0\COMMO.Network.Tests.dll] Unable to load types from the test source '\bin\x64\Release\netcoreapp2.0\COMMO.Network.Tests.dll'. Some or all of the tests in this source may not be discovered.

It seems that, for some reason, Span and ReadOnlySpan references are not found. Removing them or trying any tests without them works perfectly.

**Comment by igorquintaes** [comment]
Could we change MSTest lib to NUnit or XUnit, or it is not an option?

**Comment by Mirandatz** [comment]
Changed to xUnit. Problem solved :)
