### ISSUE TITLE
Standardize coordinate / position type

### ISSUE THREAD

**Issue by Mirandatz** [CoreOpenMMO/CoreOpenMMO#48]
Some classes / methods expect coordinate to be uint16, while some expect a uint32 and the "Position" class itself uses ints.
We should change all classes and methods to use a single type, being careful to check if we are doing some sort of bit-hackery that actually requires a type to be unsigned (or smaller) when doing such changes.

**Comment by jsapparts** [comment]
Position should be: x = uint16, y = uint16, z = byte .  UInt16.MaxValue is used by map editor, and others implementations, and should be enough for all the maps.

**Comment by Mirandatz** [comment]
I think we should try to _always_ use the "Position" class to represent a coordinate so that if we decide to change from uint16 to something else, it's a single-class modification.

I personally prefer int32 instead of uint16... I really feel 2^16 is a small value for a "world width".
